compose_base_path: /opt/docker

service_config:
  uptime-kuma:
    kind: docker
    version: 2.4.0
    dirs: 
      - { path: data, mode: "0755" }
    caddy:
      template: uptime-kuma
  ntfy:
    kind: docker
    version: v2.26.0
    dirs: 
      - { path: data, mode: "0755" }
      - { path: cache, mode: "0755" }
    caddy:
      reverse_proxy_opts:
        - "flush_interval -1"
  openwebui:
    kind: docker
    version: 0.9.5
    dirs:
      - { path: data,   mode: "0755", owner: 1000, group: 1000}
  diun:
    kind: docker
    version: 4.33
    dirs: 
      - { path: data, mode: "0755" }
  vaultwarden:
    kind: docker
    version: 1.37.1
    dirs: 
      - { path: data, mode: "0755" }
    caddy: 
      reverse_proxy_opts:
        - "header_up X-Real-IP {remote_host}"

  # Non-Docker
  forgejo:
    kind: forgejo

  docs:
    kind: static
    caddy:
      template: docs
      root: /srv/docs
