---
vault_admin_pass: "{{ vault_vaultwarden_secret }}"
vault_compose_dir: "/opt/docker/vaultwarden"
bw_release: 2026.7.0

# Defaults for insert_secret
vw_overwrite: false
vw_secrets: []
vw_gen_cmd: "openssl rand -hex 32"

# API keys
bw_client_id: "{{ vault_bw_client_id}}"
bw_client_secret: "{{ vault_bw_client_secret }}"
