---
- name: Restart sshd
  service:
    name: ssh
    state: restarted

- name: Reload auditd rules
  command: augenrules --load

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
