---
- name: Install pipx
  ansible.builtin.apt:
    name: pipx
    state: present

- name: Install hf cli
  ansible.builtin.shell:
    cmd: curl -LsSf https://hf.co/cli/install.sh | bash
    creates: /usr/local/bin/hf
  
- name: Download models
  ansible.builtin.command:
    argv:
      - "{{ llama_cpp_huggingface_cli }}"
      - download
      - "{{ item.hf_repo }}"
      - --include
      - "{{ item.hf_file }}"
      - --local-dir
      - "{{ llama_cpp_models_dir }}"
  #environment:
  #  HF_TOKEN: "{{ vault_hf_token }}"
  args:
    creates: "{{ llama_cpp_models_dir }}/{{ item.hf_file }}"
  loop: "{{ llama_models }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.download

- name: Deploy llama.cpp model presets
  ansible.builtin.template:
    src: presets.ini.j2
    dest: "{{ llama_cpp_preset_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart llama-server
