---
- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload

- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded

- name: Restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
