---
- name: Install dependencies
  ansible.builtin.apt:
    name: 
      - unzip
    state: present 

- name: Determine bw CLI architecture
  ansible.builtin.set_fact:
    bw_arch: "{{ 'linux-arm64' if ansible_facts['architecture'] in ['aarch64', 'arm64'] else 'linux' }}"

- name: Install bw CLI
  ansible.builtin.unarchive:
    src: "https://github.com/bitwarden/clients/releases/download/cli-v{{ bw_release }}/bw-{{ bw_arch }}-{{ bw_release }}.zip"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'

- name: Set server
  ansible.builtin.command: "bw config server {{ vault_domain }}"
